[[CURRENCIES]]
code="ONX"
issuer="GBUNENB6AYNTVUWGFG2Y63HX5PIYVENTHOQ3TAGW2NDYCV2BPA3NZQ65"
name="Saadu Abdurrazak Jibrin"
desc="ONX Token on Pi Testnet"
image="https://saaduabdurrazak86-wq.github.io/onx-token/logo.png"
